management:
  endpoints:
    access:
      default: unrestricted  # ✅ enabled-by-default → access.default 변경
    web:
      base-path: /actuator
      exposure:
        include: [ "info", "health", "refresh", "beans", "configprops", "env", "mappings" ]
  endpoint:
    configprops:
      show-values: when_authorized
  info:
    git:
      enabled: true

# ELK 스택 5044 Logstash 연결 포트
log:
  server:
    host: 127.0.0.1
    port: 5044